instagram:
  server:
    serverDirPath: D:\IDEA-workspace\Data\
    imgSrcPath: http://localhost:8080/upload/
server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/

spring:
  application:
    name: instagram-search-provider
  datasource:
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=Asia/Shanghai
    username: root
    password: ufo950327
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true